name: Run PHP and Python Scripts

on:
  workflow_dispatch:  # Manual trigger

jobs:
  run-php-python:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to get the latest code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # List all files in the repository to check the file structure
    - name: List all files in the repository
      run: ls -R
    
    # Set up PHP (using PHP 8.1)
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    # Check PHP version to ensure it's installed properly
    - name: Check PHP version
      run: php -v

    # Run PHP files (adjust path if needed)
    - name: Run PHP scripts
      run: |
        php index.php
        php db.php
        php sv.php
        php s.php
    
    # Set up Python (using Python 3.10)
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install Python dependencies (from requirements.txt)
    - name: Install Python dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run Python image comparison analysis (using compare.py)
    - name: Run Python image comparison
      run: |
        python compare.py uploads/matched_output.jpg uploads/no_match_found.jpg
    
    # List contents of uploads folder for debugging
    - name: List Uploads folder contents
      run: ls -l uploads/
