name: Run PHP and Python Scripts

on:
  workflow_dispatch:

jobs:
  run-php-python:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: familytree
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List repository contents
      run: ls -l

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Check PHP version
      run: php -v

    - name: Set up MySQL client
      run: sudo apt-get install -y default-mysql-client

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h 127.0.0.1 -uroot -prootpassword --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Test MySQL connection
      run: mysql -h 127.0.0.1 -uroot -prootpassword -e "SHOW DATABASES;"

    # Optional: Import database schema if you have it
    # - name: Import SQL schema
    #   run: |
    #     mysql -h 127.0.0.1 -uroot -prootpassword familytree < schema.sql

    - name: Run PHP scripts
      run: |
        php index.php
        php s.php
       
        php sv.php

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python image comparison
      run: |
        python compare.py uploads/matched_output.jpg uploads/no_match_found.jpg

    - name: List Uploads folder contents
      run: ls -l uploads/
